// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHpdIwC5E5jVjWK-dzpaAAtzYQkl7Q8EY',
    appId: '1:1078729692650:web:d2d58394c42d7718618e93',
    messagingSenderId: '1078729692650',
    projectId: 'noteify-e6865',
    authDomain: 'noteify-e6865.firebaseapp.com',
    storageBucket: 'noteify-e6865.appspot.com',
    measurementId: 'G-TZ0STD3WVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhw2hRMVWjjip1pCfHHCXv2Hsosx1JSmg',
    appId: '1:1078729692650:android:f4c7fa1fbcd66b48618e93',
    messagingSenderId: '1078729692650',
    projectId: 'noteify-e6865',
    storageBucket: 'noteify-e6865.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ-QURWk9ihmzZYbvMJ-leGCXKD6h8e8g',
    appId: '1:1078729692650:ios:7e41f3cdeefe0bb0618e93',
    messagingSenderId: '1078729692650',
    projectId: 'noteify-e6865',
    storageBucket: 'noteify-e6865.appspot.com',
    iosBundleId: 'com.example.noteifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ-QURWk9ihmzZYbvMJ-leGCXKD6h8e8g',
    appId: '1:1078729692650:ios:7e41f3cdeefe0bb0618e93',
    messagingSenderId: '1078729692650',
    projectId: 'noteify-e6865',
    storageBucket: 'noteify-e6865.appspot.com',
    iosBundleId: 'com.example.noteifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHpdIwC5E5jVjWK-dzpaAAtzYQkl7Q8EY',
    appId: '1:1078729692650:web:eacd66a0d12b8ade618e93',
    messagingSenderId: '1078729692650',
    projectId: 'noteify-e6865',
    authDomain: 'noteify-e6865.firebaseapp.com',
    storageBucket: 'noteify-e6865.appspot.com',
    measurementId: 'G-1S9LMFVX36',
  );
}
